BEGIN;

ALTER TABLE songs ALTER COLUMN audio_url TYPE VARCHAR(1024);
ALTER TABLE media_assets ALTER COLUMN storage_key TYPE VARCHAR(1024);

ALTER TABLE media_assets ADD COLUMN IF NOT EXISTS bucket_name VARCHAR(255);
ALTER TABLE media_assets ADD COLUMN IF NOT EXISTS etag VARCHAR(128);
ALTER TABLE media_assets ADD COLUMN IF NOT EXISTS last_modified_at TIMESTAMPTZ;
ALTER TABLE media_assets ADD COLUMN IF NOT EXISTS imported_at TIMESTAMPTZ;
ALTER TABLE media_assets ADD COLUMN IF NOT EXISTS import_source VARCHAR(64);

CREATE UNIQUE INDEX IF NOT EXISTS uk_media_assets_storage_object
    ON media_assets (storage_provider, bucket_name, storage_key)
    WHERE storage_key IS NOT NULL
      AND status <> 'DELETED';

CREATE INDEX IF NOT EXISTS idx_media_assets_storage_lookup
    ON media_assets (storage_provider, bucket_name, storage_key);

CREATE TABLE IF NOT EXISTS r2_import_jobs (
    r2_import_job_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    bucket_name VARCHAR(255) NOT NULL,
    prefix VARCHAR(512),
    status VARCHAR(32) NOT NULL DEFAULT 'RUNNING',
    scanned_objects INTEGER NOT NULL DEFAULT 0,
    imported_songs INTEGER NOT NULL DEFAULT 0,
    skipped_objects INTEGER NOT NULL DEFAULT 0,
    failed_objects INTEGER NOT NULL DEFAULT 0,
    started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finished_at TIMESTAMPTZ,
    error_message TEXT,
    CONSTRAINT ck_r2_import_jobs_status
        CHECK (status IN ('RUNNING', 'COMPLETED', 'COMPLETED_WITH_ERRORS', 'FAILED')),
    CONSTRAINT ck_r2_import_jobs_counts
        CHECK (
            scanned_objects >= 0
            AND imported_songs >= 0
            AND skipped_objects >= 0
            AND failed_objects >= 0
        )
);

CREATE TABLE IF NOT EXISTS r2_import_job_items (
    r2_import_job_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    r2_import_job_id UUID NOT NULL,
    bucket_name VARCHAR(255) NOT NULL,
    object_key VARCHAR(1024) NOT NULL,
    object_size_bytes BIGINT,
    object_last_modified_at TIMESTAMPTZ,
    etag VARCHAR(128),
    status VARCHAR(32) NOT NULL,
    reason VARCHAR(255),
    song_id UUID,
    media_asset_id UUID,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_r2_import_job_items_job
        FOREIGN KEY (r2_import_job_id)
        REFERENCES r2_import_jobs (r2_import_job_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_r2_import_job_items_song
        FOREIGN KEY (song_id)
        REFERENCES songs (song_id)
        ON DELETE SET NULL,
    CONSTRAINT fk_r2_import_job_items_media_asset
        FOREIGN KEY (media_asset_id)
        REFERENCES media_assets (media_asset_id)
        ON DELETE SET NULL,
    CONSTRAINT ck_r2_import_job_items_status
        CHECK (status IN ('IMPORTED', 'SKIPPED', 'FAILED')),
    CONSTRAINT ck_r2_import_job_items_size
        CHECK (object_size_bytes IS NULL OR object_size_bytes >= 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_r2_import_job_items_job_object
    ON r2_import_job_items (r2_import_job_id, object_key);

CREATE INDEX IF NOT EXISTS idx_r2_import_jobs_started_at
    ON r2_import_jobs (started_at DESC);

CREATE INDEX IF NOT EXISTS idx_r2_import_job_items_job_status
    ON r2_import_job_items (r2_import_job_id, status);

CREATE INDEX IF NOT EXISTS idx_r2_import_job_items_media_asset_id
    ON r2_import_job_items (media_asset_id);

COMMIT;
